### ISSUE TITLE
See Gauge Info Blank + Spelling

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#102]
On River Detail "See Gauge Info" goes to a blank page, and also Gauge should be spelled Gage everywhere possible.

**Comment by RacIVRnr** [comment]
I find this decision by the USGS to be indefensible. Their page cites "The spelling of “gage” is part of our very rich USGS history." Then it goes on to tell of the "forward-thinking graduate student named Frederick H. Newell" who "reasoned that “gage” was the proper Saxon spelling before the Norman influence added a 'u'. USGS historian Robert Follansbee speculated that Newell might have also been influenced by the adoption of “gage” in the Standard Dictionary (the first dictionary produced by Funk and Wagnalls)."

However ... if you search any number of modern dictionaries, you will find virtual unanimity that:
"**Gage is the spelling of an obsolescent word** meaning a pledge, a challenge, etc.
Gauge is the spelling to use when you measure measurement, estimate, or standard."

So, because one man's ignorance (in the late 1800's) is part of USGS history, we are doomed to propagate that ignorance in the 21st century?

**Comment by duffek** [comment]
While I admire your passion, the entire AW system runs on top of the USGS system. Your opinion on their decisions with this should likely go directly to them. -- Fixed in Build 5
