### ISSUE TITLE
Gage readings on river pages and lists not updating (Critical)

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#119]
I see a lot of rivers running on the list page and the river pages but when I click through to the gage it is clear that these pages are reflecting old data: 

See this looks like it is running:

![IMG_6297](https://user-images.githubusercontent.com/7936679/68957385-ea43f600-0797-11ea-9f05-0906c83b5418.PNG)

But it is not:

![IMG_6298](https://user-images.githubusercontent.com/7936679/68957409-f7f97b80-0797-11ea-84ff-0b4af4adc480.PNG)

**Comment by duffek** [comment]
I've been focusing on this today. It seems that the code that is looking for out-dated data (10mins or longer) isn't triggering the udpate on the Runs, Favorites, or Map. Should be a simple fix once I understand why it's happening.

**Comment by duffek** [comment]
Of all things, I was using `lastGuageReading` instead of `currentGaugeReading` for some odd reason. It'd be good to map all of these out in the new API so we have a defined list in the Repo README for new developers. This was likely something I did when I was first making changes. This also exposed a bug to the Favorites listing. Fixed in TestFlight Build 19
