### ISSUE TITLE
App not recognizing my username/email for password recovery

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#224]
ON TESTFLIGHT - I tried to add a photo and it required me to log in (good). I could not remember my password so clicked on Forgot my Password. When I enter my email address it did not recognize the email address. 

I went back to the website and got my password and went back tot he app and logged in just fine. So this is just a password recovery issue. 
![IMG_5905](https://user-images.githubusercontent.com/7936679/126682154-acaf0aed-03d1-4e52-a300-7db7bcfc9903.jpg)

**Comment by Gregliest** [comment]
I believe that's just a webview, are you sure you typed in your email correctly?

**Comment by AWKevin** [comment]
Yes I tried many times.

**Comment by Gregliest** [comment]
Hmm, you're right. I think this is a server issue. I verified that the urls for the login page and forgot password page are going to the same place. Maybe the server is treating mobile requests differently? cc @ryangroth5

**Comment by Gregliest** [comment]
@AWKevin I think I figured this one out, this form appears to be caps sensitive. "Gregliest@gmail.com" did not work, but "gregliest@gmail.com" did work on both mobile and desktop. Did you use something like "Kevin..." instead of "kevin"? 

@ryangroth5 Password reset shouldn't be caps sensitive, right? I can make an issue on the api.

**Comment by Gregliest** [comment]
https://github.com/AmericanWhitewater/wh2o/issues/2372
