### ISSUE TITLE
Panning on the map does not bring up new river icons

### ISSUE THREAD

**Issue by AWKevin** [AmericanWhitewater/aw-ios#89]
When I click on map in the bottom menu I only see Icons for my state, but then if I pan the map to another region river icons do not appear and there is no obvious way to make them appear. (Use case: I want to explore rivers in Utah where I am headed in a couple weeks, and the app would not let me do that.)

**Comment by duffek** [comment]
This is going to take a new river call and fixing the filtering. This isn't working since right now in this version we're only pulling the data from the selected region. After this is fixed, it'll create a bounding box of regions that you pan into. This will let this feature come back. After we get the CoreData feature added back in this will also become a non-issue since most of the data will be stored locally. 

This feature will likely be back next week.

**Comment by duffek** [comment]
Fixed on TestFlight Build 11
